export default {
  ADD_COMPARE_FRIEND_ID: "ADD_COMPARE_FRIEND_ID",
  REMOVE_COMPARE_FRIEND_ID: "REMOVE_COMPARE_FRIEND_ID",
  GET_FRIEND_COMPARE_REQUEST: "GET_FRIEND_COMPARE_REQUEST",
  SAVE_FRIEND: "SAVE_FRIEND",
  REMOVE_FRIEND_COMPARE: "REMOVE_FRIEND_COMPARE",
  LOADING_COMPARE_DONE: "LOADING_COMPARE_DONE",
  LOADING_REMOVE_DONE: "LOADING_REMOVE_DONE",
  READD_FRIEND_COMPARE: "READD_FRIEND_COMPARE"
};
